id: I50154DD4
legacy_id: P004520
ocr_import_info:
  bdrc_scan_id: W1PD88977
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T10:19:40'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-01T05:03:16.541818+00:00'
last_modified: 2022-09-01 13:03:24.242287
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1PD88977
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1PD88977
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དཀར་མཛེས་ཁུལ་རིག་གནས་ལོ་རྒྱུས་ཀྱི་དཔྱད་ཡིག ༼༢༽
statistics:
  ocr_word_mean_confidence_index: 0.5302068829971083
  ocr_word_median_confidence_index: 0.4699999988079071
quality: null
bases:
  I1KG17051:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG17051
      total_pages: 102
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG17051.txt
    statistics:
      ocr_word_median_confidence_index: 0.4699999988079071
      ocr_word_mean_confidence_index: 0.5302068829971083
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
