id: I50154DD4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T10:20:23+00:00'
last_modified: '2022-06-08T01:39:48.023972+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD88977
  title: དཀར་མཛེས་ཁུལ་རིག་གནས་ལོ་རྒྱུས་ཀྱི་དཔྱད་ཡིག ༼༢༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    42AE:
      image_group_id: I1KG17051
      title: ''
      total_pages: 102
      order: 1
      base_file: 42AE.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
