id: P004520
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 11:29:16.842260
source_metadata:
  id: bdr:W1PD88977
  title: དཀར་མཛེས་ཁུལ་རིག་གནས་ལོ་རྒྱུས་ཀྱི་དཔྱད་ཡིག ༼༢༽
  author: ''
  volumes:
    30f410986d124b2293cf44d26df2fc4a:
      image_group_id: I1KG17051
      title: ''
      volume_number: 1
      total_pages: 102
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
